/**
 * 页面table表格配置
 * xiaobai
 * 2019.12.11
 */
export const pageTableConfig = {
  // 书籍数据配置(作品PV)
  bookData: {
    noRepeatSum: {
      id: false,
      site_id: false,
      timeline: true,
      platform: false,
      book_id: false,
      author_name: true,
      pv: true,
      uv: true,
      users: true,
      section_id: false,
      class_id: false,
      book_name: true,
      outsite: false,
      group_count: true,
      user_id_count: false,
      book_id_count: true
    },
    checkedSum: {
      id: false,
      site_id: true,
      timeline: true,
      platform: true,
      book_id: true,
      author_name: true,
      pv: true,
      uv: true,
      users: true,
      section_id: true,
      class_id: true,
      book_name: true,
      outsite: true,
      group_count: true,
      user_id_count: false,
      book_id_count: true
    },
    sortSum: {
      id: false,
      site_id: false,
      timeline: true,
      platform: false,
      book_id: true,
      author_name: false,
      pv: true,
      uv: true,
      users: true,
      section_id: false,
      class_id: false,
      book_name: false,
      outsite: false,
      group_count: false,
      user_id_count: false,
      book_id_count: true
    }
  },
  // 书籍数据配置(作品PV)
  chapterPvData: {
    noRepeatSum: {
      id: false,
      site_id: false,
      timeline: true,
      platform: false,
      book_id: true,
      chapter_id: true,
      chapter_code: true,
      chapter_title: false,
      author_name: true,
      pv: true,
      uv: true,
      users: true,
      section_id: false,
      class_id: false,
      book_name: true,
      outsite: false,
      group_count: true,
      user_id_count: false,
      book_id_count: true
    },
    checkedSum: {
      id: false,
      site_id: true,
      timeline: true,
      platform: true,
      book_id: true,
      chapter_id: true,
      chapter_code: true,
      chapter_title: true,
      author_name: true,
      pv: true,
      uv: true,
      users: true,
      section_id: false,
      class_id: true,
      book_name: true,
      outsite: false,
      group_count: true,
      user_id_count: false,
      book_id_count: true
    },
    sortSum: {
      id: false,
      site_id: false,
      timeline: true,
      platform: false,
      book_id: true,
      chapter_id: true,
      chapter_code: true,
      chapter_title: true,
      author_name: false,
      pv: true,
      uv: true,
      users: true,
      section_id: false,
      class_id: false,
      book_name: false,
      outsite: false,
      group_count: false,
      user_id_count: false,
      book_id_count: true
    }
  },
  // 书籍推荐配置(推荐位统计)
  bookRecom: {
    noRepeatSum: {
      id: false,
      tj_page: true,
      timeline: true,
      book_id: true,
      section_id: false,
      class_id: false,
      book_name: true,
      author_name: true,
      tj_pos: true,
      outsite: false,
      pv: true,
      uv: true,
      site_id: false,
      platform: false,
      group_count: true,
      user_id_count: false,
      book_id_count: true
    },
    checkedSum: {
      id: false,
      tj_page: true,
      timeline: true,
      book_id: true,
      section_id: true,
      class_id: true,
      book_name: true,
      author_name: true,
      tj_pos: true,
      outsite: true,
      pv: true,
      uv: true,
      site_id: true,
      platform: true,
      group_count: true,
      user_id_count: false,
      book_id_count: true
    },
    sortSum: {
      id: false,
      tj_page: false,
      timeline: true,
      book_id: true,
      section_id: false,
      class_id: false,
      book_name: false,
      author_name: false,
      tj_pos: true,
      outsite: false,
      pv: true,
      uv: true,
      site_id: false,
      platform: false,
      group_count: false,
      user_id_count: false,
      book_id_count: true
    }
  },
  // 书籍消费配置(作品消费)
  bookCost: {
    noRepeatSum: {
      id: false,
      site_id: false,
      timeline: true,
      platform: false,
      book_id: true,
      cost_total: true,
      cost_coin: true,
      cost_chapters: true,
      cost_coin_chapters: true,
      cost_user: true,
      cost_coin_user: true,
      section_id: false,
      class_id: false,
      book_name: true,
      outsite: false,
      author_name: true,
      group_count: true,
      user_id_count: false,
      book_id_count: true
    },
    checkedSum: {
      id: false,
      site_id: true,
      timeline: true,
      platform: true,
      book_id: true,
      cost_total: true,
      cost_coin: true,
      cost_chapters: true,
      cost_coin_chapters: true,
      cost_user: true,
      cost_coin_user: true,
      section_id: true,
      class_id: true,
      book_name: true,
      outsite: true,
      author_name: true,
      group_count: true,
      user_id_count: false,
      book_id_count: true
    },
    sortSum: {
      id: false,
      site_id: false,
      timeline: true,
      platform: false,
      book_id: true,
      cost_total: true,
      cost_coin: true,
      cost_chapters: true,
      cost_coin_chapters: true,
      cost_user: true,
      cost_coin_user: true,
      section_id: false,
      class_id: false,
      book_name: false,
      outsite: false,
      author_name: false,
      group_count: false,
      user_id_count: false,
      book_id_count: true
    }
  },
  // 书籍互动消费配置（作品互动）
  bookAct: {
    noRepeatSum: {
      id: false,
      site_id: false,
      timeline: true,
      platform: false,
      book_id: true,
      bookshelf: true,
      vote: true,
      comment: true,
      share: true,
      recommend: true,
      reward: true,
      activity: true,
      section_id: false,
      class_id: false,
      book_name: true,
      outsite: false,
      author_name: true,
      average_cost_user: true,
      high_cost_user: true,
      all_cost_user: true,
      group_count: true,
      user_id_count: false,
      book_id_count: true
    },
    checkedSum: {
      id: false,
      site_id: true,
      timeline: true,
      platform: true,
      book_id: true,
      bookshelf: true,
      vote: true,
      comment: true,
      share: true,
      recommend: true,
      reward: true,
      activity: true,
      section_id: true,
      class_id: true,
      book_name: true,
      outsite: true,
      author_name: true,
      average_cost_user: true,
      high_cost_user: true,
      all_cost_user: true,
      group_count: true,
      user_id_count: false,
      book_id_count: true
    },
    sortSum: {
      id: false,
      site_id: false,
      timeline: true,
      platform: false,
      book_id: true,
      bookshelf: true,
      vote: true,
      comment: true,
      share: true,
      recommend: true,
      reward: true,
      activity: true,
      section_id: false,
      class_id: false,
      book_name: false,
      outsite: false,
      author_name: false,
      average_cost_user: true,
      high_cost_user: true,
      all_cost_user: true,
      group_count: false,
      user_id_count: false,
      book_id_count: true
    }
  },
  // 充值数据配置(充值统计)
  payData: {
    noRepeatSum: {
      timeline: true,
      hour: true,
      site_id: false,
      platform: false,
      order_num: true,
      pay_money: true,
      user_num: true,
      pay_num: true,
      fuel_money: true,
      fuel_user: true,
      year_money: true,
      year_user: true,
      pay_channel: true,
      discount_money: true,
      discount_user: true,
      diamand_money: true,
      diamand_user: true,
      pay_channel_tag: true,
      currency: true,
      group_count: true,
      fc: true,
      user_id_count: false,
      book_id_count: false
    },
    checkedSum: {
      timeline: true,
      hour: true,
      site_id: true,
      platform: true,
      order_num: true,
      pay_money: true,
      user_num: true,
      pay_num: true,
      fuel_money: true,
      fuel_user: true,
      year_money: true,
      year_user: true,
      pay_channel: true,
      discount_money: true,
      discount_user: true,
      diamand_money: true,
      diamand_user: true,
      pay_channel_tag: true,
      currency: true,
      group_count: true,
      fc: true,
      user_id_count: false,
      book_id_count: false
    },
    sortSum: {
      timeline: true,
      hour: true,
      site_id: false,
      platform: false,
      order_num: true,
      pay_money: true,
      user_num: true,
      pay_num: true,
      fuel_money: true,
      fuel_user: true,
      year_money: true,
      year_user: true,
      pay_channel: false,
      discount_money: true,
      discount_user: true,
      diamand_money: true,
      diamand_user: true,
      pay_channel_tag: false,
      currency: false,
      group_count: false,
      fc: false,
      user_id_count: false,
      book_id_count: false
    }
  },
  // 充值用户配置
  payUser: {
    noRepeatSum: {
      user_id: true,
      timeline: true,
      site_id: false,
      platform: false,
      order_num: true,
      pay_money: true,
      pay_num: true,
      pay_channel: true,
      pay_channel_tag: true,
      currency: true,
      group_count: true,
      user_id_count: true,
      book_id_count: false
    },
    checkedSum: {
      user_id: true,
      timeline: true,
      site_id: true,
      platform: true,
      order_num: true,
      pay_money: true,
      pay_num: true,
      pay_channel: true,
      pay_channel_tag: true,
      currency: true,
      group_count: true,
      user_id_count: true,
      book_id_count: false
    },
    sortSum: {
      user_id: true,
      timeline: true,
      site_id: false,
      platform: false,
      order_num: true,
      pay_money: true,
      pay_num: true,
      pay_channel: false,
      pay_channel_tag: false,
      currency: false,
      group_count: false,
      user_id_count: true,
      book_id_count: false
    }
  },
  // 消费数据配置
  costData: {
    noRepeatSum: {
      timeline: true,
      site_id: false,
      platform: false,
      new_user: true,
      live_user: true,
      group_count: true,
      user_id_count: true,
      book_id_count: true
    },
    checkedSum: {
      timeline: true,
      site_id: true,
      platform: true,
      new_user: true,
      live_user: true,
      group_count: true,
      user_id_count: true,
      book_id_count: true
    },
    sortSum: {
      timeline: true,
      site_id: true,
      platform: true,
      new_user: true,
      live_user: true,
      group_count: false,
      user_id_count: true,
      book_id_count: true
    }
  },
  // 消费用户配置(用户消费详情)
  costUser: {
    noRepeatSum: {
      id: false,
      site_id: false,
      timeline: true,
      platform: false,
      book_id: true,
      book_name: true,
      author_name: true,
      user_id: true,
      cost_total: true,
      cost_coin: true,
      chapters_total: true,
      coin_chapters: true,
      section_id: false,
      class_id: false,
      outsite: false,
      group_count: true,
      user_id_count: true,
      book_id_count: true
    },
    checkedSum: {
      id: false,
      site_id: true,
      timeline: true,
      platform: true,
      book_id: true,
      book_name: true,
      author_name: true,
      user_id: true,
      cost_total: true,
      cost_coin: true,
      chapters_total: true,
      coin_chapters: true,
      section_id: true,
      class_id: true,
      outsite: true,
      group_count: true,
      user_id_count: true,
      book_id_count: true
    },
    sortSum: {
      id: false,
      site_id: false,
      timeline: true,
      platform: false,
      book_id: true,
      book_name: false,
      author_name: false,
      user_id: true,
      cost_total: true,
      cost_coin: true,
      chapters_total: true,
      coin_chapters: true,
      section_id: false,
      class_id: false,
      outsite: false,
      group_count: true,
      user_id_count: true,
      book_id_count: true
    }
  },
  // 章节列表
  bookChapter: {
    noRepeatSum: {
      book_id: true,
      chapter_id: true,
      timeline: true,
      site_id: false,
      pv: true,
      uv: true,
      users: true,
      // vip_users: true
    },
    checkedSum: {
      book_id: true,
      chapter_id: true,
      timeline: true,
      site_id: true,
      pv: true,
      uv: true,
      users: true
      // vip_users: true
    },
    sortSum: {
      book_id: true,
      chapter_id: true,
      timeline: true,
      site_id: true,
      pv: true,
      uv: true,
      users: true
      // vip_users: true
    }
  },
  // app推广数据
  appExtendData: {
    noRepeatSum: {
      timeline:true,
      site_id:true,
      daa_channel:true,
      daa_account_name:true,
      platform:true,
      daa_series:true,
      book_id:true,
      daa_show_times:true,
      daa_show_users:true,
      click_an_rate:true,
      daa_cost:true,
      daa_install_users:true,
      uninstalled:true,
      daa_pay:true,
      InconsistentReturn:true,
      daa_pay_times:true,
      daa_pay_users:true,
      daa_editor:true
    },
    checkedSum: {
      timeline:true,
      site_id:true,
      daa_channel:true,
      daa_account_name:true,
      platform:true,
      daa_series:true,
      book_id:true,
      daa_show_times:true,
      daa_show_users:true,
      click_an_rate:true,
      daa_cost:true,
      daa_install_users:true,
      uninstalled:true,
      daa_pay:true,
      InconsistentReturn:true,
      daa_pay_times:true,
      daa_pay_users:true,
      daa_editor:true
    },
    sortSum: {
      timeline:true,
      site_id:true,
      daa_channel:true,
      daa_account_name:true,
      platform:true,
      daa_series:true,
      book_id:true,
      daa_show_times:true,
      daa_show_users:true,
      click_an_rate:true,
      daa_cost:true,
      daa_install_users:true,
      uninstalled:true,
      daa_pay:true,
      InconsistentReturn:true,
      daa_pay_times:true,
      daa_pay_users:true,
      daa_editor:true
    }
  },
  // 日活月活用户
  dayMonthLife: {
    noRepeatSum: {
      site_id: false,
      platform: false,
      timeline: true,
      order_date:true,
      reg_days:true,
      // plan_reg_days:true,
      order_money:true,
      order_user:true,
      total_order_money:true,
      fuel_money:true,
      fuel_user:true,
      discount_money:true,
      discount_user:true,
      diamand_money:true,
      diamand_user:true,
      new_user:true,
      live_user:true,
      daily_live_user:false,
      pay_daily_user:true,
      monthly_live_user:true,
      monthly_pay_user:true,
      daa_show_users:true,
      daa_show_times:true,
      daa_hits:true,
      daa_cost:true,
      daa_install_users:true,
      daa_pay:true,
      daa_pay_users:true,
      daa_pay_times:true,
      group_count: true,
      ltv: true
    },
    checkedSum: {
      site_id: true,
      platform: true,
      timeline: true,
      order_date:true,
      reg_days:true,
      // plan_reg_days:true,
      order_money:true,
      order_user:true,
      total_order_money:true,
      fuel_money:true,
      fuel_user:true,
      discount_money:true,
      discount_user:true,
      diamand_money:true,
      diamand_user:true,
      new_user:true,
      live_user:true,
      daily_live_user:false,
      pay_daily_user:true,
      monthly_live_user:true,
      monthly_pay_user:true,
      daa_show_users:true,
      daa_show_times:true,
      daa_hits:true,
      daa_cost:true,
      daa_install_users:true,
      daa_pay:true,
      daa_pay_users:true,
      daa_pay_times:true,
      group_count: true,
      ltv: true
    },
    sortSum: {
      site_id: false,
      platform: false,
      timeline: true,
      order_date:true,
      reg_days:true,
      // plan_reg_days:true,
      order_money:true,
      order_user:true,
      total_order_money:true,
      fuel_money:true,
      fuel_user:true,
      discount_money:true,
      discount_user:true,
      diamand_money:true,
      diamand_user:true,
      new_user:true,
      live_user:true,
      daily_live_user:false,
      pay_daily_user:true,
      monthly_live_user:true,
      monthly_pay_user:true,
      daa_show_users:true,
      daa_show_times:true,
      daa_hits:true,
      daa_cost:true,
      daa_install_users:true,
      daa_pay:true,
      daa_pay_users:true,
      daa_pay_times:true,
      group_count: false,
      ltv: false
    }
  },
  // uv排行榜
  uvRecords: {
    noRepeatSum: {
      book_id: true,
      book_name: true,
      platform: true,
      site_id: true,
      event_type: true,
      uv: true,
    },
    checkedSum: {
      book_id: true,
      book_name: true,
      platform: true,
      site_id: true,
      event_type: true,
      uv: true,
    },
    sortSum: {
      book_id: true,
      book_name: true,
      platform: true,
      site_id: true,
      event_type: true,
      uv: true,
    }
  },
  // 增幅排行榜
  growThRate: {
    noRepeatSum: {
      book_id: true,
      book_name: true,
      platform: true,
      site_id: true,
      event_type: true,
      start_uv: true,
      uv_incr: true,
    },
    checkedSum: {
      book_id: true,
      book_name: true,
      platform: true,
      site_id: true,
      event_type: true,
      start_uv: true,
      uv_incr: true,
    },
    sortSum: {
      book_id: true,
      book_name: true,
      platform: true,
      site_id: true,
      event_type: true,
      start_uv: true,
      uv_incr: true,
    }
  },
  // 推送列表
  publishList: {
    noRepeatSum: {
      site_code: true,
      book_id: true,
      app_channel: true,
      status: true,
      add_time: true,
      complete_time: true,
      send_time: true,
      send_type: true,
      send_model: true,
      topic: true,
      book_prev_five_const: true,
      book_prev_five_premium: true,
      book_prev_five_num: true,
      book_next_five_const: true,
      book_next_five_premium: true,
      book_next_five_num: true,
      book_prev_five_pv: true,
      book_prev_five_uv: true,
      book_next_five_pv: true,
      book_next_five_uv: true,
    },
    checkedSum: {
      site_code: true,
      book_id: true,
      app_channel: true,
      status: true,
      add_time: true,
      complete_time: true,
      send_time: true,
      send_type: true,
      send_model: true,
      topic: true,
      book_prev_five_const: true,
      book_prev_five_premium: true,
      book_prev_five_num: true,
      book_next_five_const: true,
      book_next_five_premium: true,
      book_next_five_num: true,
      book_prev_five_pv: true,
      book_prev_five_uv: true,
      book_next_five_pv: true,
      book_next_five_uv: true,
    },
    sortSum: {
      site_code: false,
      book_id: true,
      app_channel: true,
      status: true,
      add_time: true,
      complete_time: true,
      send_time: true,
      send_type: false,
      send_model: true,
      topic: true,
      book_prev_five_const: true,
      book_prev_five_premium: true,
      book_prev_five_num: true,
      book_next_five_const: true,
      book_next_five_premium: true,
      book_next_five_num: true,
      book_prev_five_pv: true,
      book_prev_five_uv: true,
      book_next_five_pv: true,
      book_next_five_uv: true,
    }
  },
  // 专属魔豆数据
  exclusBean: {
    noRepeatSum: {
      event_id: true,
      event_name: true,
      event_status: true,
      active_time: true,
      book_id: true,
      book_name: true,
      magic_bean_num: true,
      receive_num: true,
      usage_num: true,
      run_out_num: true,
      sub_num	: true,
      // sub_cost_coin_sum: true,
      usage_rate: true,
      run_out_rate: true,
      // conversion_rates: true,
    },
    checkedSum: {
      event_id: true,
      event_name: true,
      event_status: true,
      active_time: true,
      book_id: true,
      book_name: true,
      magic_bean_num: true,
      receive_num: true,
      usage_num: true,
      run_out_num: true,
      sub_num	: true,
      // sub_cost_coin_sum: true,
      usage_rate: true,
      run_out_rate: true,
      // conversion_rates: true,
    },
    sortSum: {
      event_id: true,
      event_name: false,
      event_status: false,
      active_time: true,
      book_id: true,
      book_name: false,
      magic_bean_num: true,
      receive_num: true,
      usage_num: true,
      run_out_num: true,
      sub_num	: true,
      // sub_cost_coin_sum: true,
      usage_rate: true,
      run_out_rate: true,
      // conversion_rates: true,
    }
  },
  // 充值项统计
  rechargeStatics: {
    noRepeatSum: {
      date: true,
      fee_sum: true,
      coin_sum: true,
      topup_num: true,
      recharge_item: true,
      user_num: true,
      proportion: true,
      group_count: true
    },
    checkedSum: {
      date: true,
      fee_sum: true,
      coin_sum: true,
      topup_num: true,
      recharge_item: true,
      user_num: true,
      proportion: true,
      group_count: true
    },
    sortSum: {
      date: true,
      fee_sum: true,
      coin_sum: true,
      topup_num: true,
      recharge_item: true,
      user_num: true,
      proportion: true,
      group_count: false
    }
  },
  // 关键词统计
  keyWordStatics: {
    noRepeatSum: {
      keyword: true,
      searches_number: true,
      site_id: true,
      timeline: true,
      group_count: true
    },
    checkedSum: {
      keyword: true,
      searches_number: true,
      site_id: true,
      timeline: true,
      group_count: true
    },
    sortSum: {
      keyword: false,
      searches_number: true,
      site_id: true,
      timeline: true,
      group_count: false
    }
  },
  // 活动对比
  activeRatio: {
    noRepeatSum: {
      site_id: true,
      timeline: true,
    },
    checkedSum: {
      site_id: true,
      timeline: true,
    },
    sortSum: {
      site_id: true,
      timeline: true,
    }
  },
  // 书籍每日统计
  bookEveryDayStatics: {
    noRepeatSum: {
      site_id: true,
      timeline: true,
      book_id: true,
      bookshelf: true,
      vote: true,
      comment: true,
      reward: true,
      average_cost_user: true,
      all_cost_user: true,
      high_cost_user: true,
    },
    checkedSum: {
      site_id: true,
      timeline: true,
      book_id: true,
      bookshelf: true,
      vote: true,
      comment: true,
      reward: true,
      average_cost_user: true,
      all_cost_user: true,
      high_cost_user: true,
    },
    sortSum: {
      site_id: true,
      timeline: true,
      book_id: true,
      bookshelf: true,
      vote: true,
      comment: true,
      reward: true,
      average_cost_user: true,
      all_cost_user: true,
      high_cost_user: true,
    }
  },

// 作品分析
  bookStatics: {
    noRepeatSum: {
      id: false,
      site_id: false,
      timeline: true,
      platform: false,
      book_id: false,
      author_name: true,
      pv: true,
      uv: true,
      // users: true,
      section_id: false,
      class_id: false,
      book_name: true,
      outsite: false,
      group_count: true,
      entire_pv: true,
      entire_uv: true,
      entire_cost_user: true,
      entire_cost_total: true,
      entire_bookshelf: true,
      cost_user: true,
      free_follow_rate: true,
      vip_rate: true,
      hundred_follow_rate: true,
      two_hundred_follow_rate: true,
      five_hundred_follow_rate: true,
      end_follow_rate: true,
      new_read_users: true,
      new_order_users: true,
      new_cost_users: true,
      ltv: true
      // cost_coin_user:true,
    },
    checkedSum: {
      id: false,
      site_id: true,
      timeline: true,
      platform: true,
      book_id: true,
      author_name: true,
      pv: true,
      uv: true,
      // users: true,
      section_id: true,
      class_id: true,
      book_name: true,
      outsite: true,
      group_count: true,
      entire_pv: true,
      entire_uv: true,
      entire_cost_user: true,
      entire_cost_total: true,
      entire_bookshelf: true,
      cost_user: true,
      free_follow_rate: true,
      vip_rate: true,
      hundred_follow_rate: true,
      two_hundred_follow_rate: true,
      five_hundred_follow_rate: true,
      end_follow_rate: true,
      new_read_users: true,
      new_order_users: true,
      new_cost_users: true,
      ltv: true
    },
    sortSum: {
      id: false,
      site_id: false,
      timeline: true,
      platform: false,
      book_id: true,
      author_name: false,
      pv: true,
      uv: true,
      // users: true,
      section_id: false,
      class_id: false,
      book_name: false,
      outsite: false,
      group_count: false,
      entire_pv: true,
      entire_uv: true,
      entire_cost_user: true,
      entire_cost_total: true,
      entire_bookshelf: true,
      cost_user: false,
      free_follow_rate: false,
      vip_rate: false,
      hundred_follow_rate: false,
      two_hundred_follow_rate: false,
      five_hundred_follow_rate: false,
      end_follow_rate: false,
      new_read_users: false,
      new_order_users: false,
      new_cost_users: false,
      ltv: false
    }
  },

}
